// File Exporter Utility for StudyX Claude-Level AI Assistant

export const downloadFile = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportAsPDF = (title: string, textContent: string) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #111; line-height: 1.6; }
        h1 { color: #5B21B6; border-bottom: 2px solid #DDD; padding-bottom: 10px; }
        pre { background: #F3F4F6; padding: 15px; border-radius: 8px; font-family: monospace; }
        footer { margin-top: 50px; font-size: 12px; color: #666; border-top: 1px solid #EEE; padding-top: 10px; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div>${textContent.replace(/\n/g, '<br/>')}</div>
      <footer>Generated by StudyX Claude-Level AI Assistant</footer>
    </body>
    </html>
  `;
  const blob = new Blob([htmlContent], { type: 'application/pdf' });
  downloadFile(blob, `${title.toLowerCase().replace(/\s+/g, '_')}.pdf`);
};

export const exportAsDOCX = (title: string, textContent: string) => {
  const docxContent = `
Title: ${title}
========================================
Generated by StudyX Claude-Level AI Assistant
Date: ${new Date().toLocaleDateString()}

${textContent}
  `;
  const blob = new Blob([docxContent], { type: 'application/msword' });
  downloadFile(blob, `${title.toLowerCase().replace(/\s+/g, '_')}.docx`);
};

export const exportAsPPTX = (title: string, textContent: string) => {
  const pptxContent = `
SLIDE 1: ${title}
----------------------------------------
- Generated by StudyX Claude-Level AI Assistant

SLIDE 2: Key Concepts & Overview
----------------------------------------
${textContent.slice(0, 300)}...

SLIDE 3: Execution & Next Steps
----------------------------------------
- Review step-by-step implementation details
- Execute code and verify output
  `;
  const blob = new Blob([pptxContent], { type: 'application/vnd.ms-powerpoint' });
  downloadFile(blob, `${title.toLowerCase().replace(/\s+/g, '_')}.pptx`);
};

export const exportAsXLSX = (title: string, textContent: string) => {
  const csvContent = `ID,Topic,Summary,Status\n1,${title},"${textContent.slice(0, 100).replace(/"/g, '""')}",COMPLETED\n`;
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  downloadFile(blob, `${title.toLowerCase().replace(/\s+/g, '_')}.xlsx`);
};

export const exportAsZIP = (title: string, codeSnippet: string) => {
  const projectArchive = `
# Project Archive: ${title}
# Generated by StudyX Claude-Level AI Assistant

=== File: index.js ===
${codeSnippet}

=== File: README.md ===
# ${title}
This code project was generated automatically by StudyX AI Assistant.
  `;
  const blob = new Blob([projectArchive], { type: 'application/zip' });
  downloadFile(blob, `${title.toLowerCase().replace(/\s+/g, '_')}_project.zip`);
};

export const exportCodeFile = (title: string, codeSnippet: string, extension: string = 'ts') => {
  const blob = new Blob([codeSnippet], { type: 'text/plain;charset=utf-8;' });
  downloadFile(blob, `${title.toLowerCase().replace(/\s+/g, '_')}.${extension}`);
};
